### PR TITLE
Feat/1 basic setup

### LINKED ISSUE #1: Set up basic dev infra
This issue covers various basic tasks that allows members to collaborate on the project. Besides the acceptance criteria below, if you have an idea to make collaboration easy and smooth, feel free to share them.

### Acceptance criteria

- [ ] Choose whether to use npm or yarn.
- [ ] Determine the directory structure considering that Aloxide is a multi-module project (a monorepo).
- [ ] Create an abstraction module as a sample of the multi-module project structure.
- [ ] Determine how to locate sources files and tests files.
- [ ] Choose the test harness for TDD.
- [ ] Write a sample unit test.
- [ ] Determine the code style and add the corresponding linter.

### Note

- See https://github.com/babel/babel/blob/master/packages/README.md for the details of the monorepo design.

### PR DESCRIPTION
**Pull request by manh-vv**
- [x]  Choose whether to use npm or yarn. => **yarn**
- [x]  Determine the directory structure considering that Aloxide is a multi-module project (a monorepo). => **monorepo (lerna)**
- [ ]  Create an abstraction module as a sample of the multi-module project structure. => **not yet, will solve in issue #7**
- [x]  Determine how to locate sources files and tests files.
- [x]  Choose the test harness for TDD. => **jest**
- [x]  Write a sample unit test.
- [x]  Determine the code style and add the corresponding linter. => **tslint + prettier**

close #1

### CODE REVIEW

**Comment by flowersinthesand** [comment]
@manh-vv What's the version of yarn?

**Comment by manh-vv** [comment]
> @manh-vv What's the version of yarn?

It should work with node >=10. I am using `yarn v1.22.0` now.

**Comment by flowersinthesand** [comment]
It seems that lerna should be installed globally too. After installing it I confirmed all scripts but yarn start works Here's the log from `yarn start`:

```
➜  aloxide git:(feat/1-basic-setup) ✗ yarn start
yarn run v1.22.4
$ lerna run start
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run start"
lerna ERR! yarn run start exited 2 in '@aloxide/bar'
lerna ERR! yarn run start stdout:
$ yarn build
$ yarn run clean && yarn run compile
$ rimraf -rf ./dist
$ tsc -p tsconfig.build.json
src/index.ts(1,31): error TS2307: Cannot find module '@aloxide/foo' or its corresponding type declarations.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run start stderr:
warning package.json: No license field
warning package.json: No license field
warning package.json: No license field
warning package.json: No license field
error Command failed with exit code 2.
error Command failed with exit code 2.
error Command failed with exit code 2.

lerna ERR! yarn run start exited 2 in '@aloxide/bar'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Is it expected?

**Comment by manh-vv** [comment]
> Is it expected?

No. Actually, I forgot to describe the initializing environment. Please follow these steps.

```bash
# install lerna globally
npm i - g lerna

# bootstrap
lerna bootstrap

# build
yarn build

# start
yarn start
```
The output should look like below:

```text
yarn build

yarn run v1.22.0
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 2 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@aloxide/foo' in 4.9s:
$ yarn run clean && yarn run compile
$ rimraf -rf ./dist
$ tsc -p tsconfig.build.json
lerna info run Ran npm script 'build' in '@aloxide/bar' in 4.9s:
$ yarn run clean && yarn run compile
$ rimraf -rf ./dist
$ tsc -p tsconfig.build.json
lerna success run Ran npm script 'build' in 2 packages in 9.8s:
lerna success - @aloxide/bar
lerna success - @aloxide/foo
✨  Done in 10.48s.

yarn start

yarn run v1.22.0
$ lerna run start
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run start"
lerna info run Ran npm script 'start' in '@aloxide/bar' in 5.4s:
$ yarn build
$ yarn run clean && yarn run compile
$ rimraf -rf ./dist
$ tsc -p tsconfig.build.json
$ node ./dist/index.js
42
lerna success run Ran npm script 'start' in 1 package in 5.4s:
lerna success - @aloxide/bar
✨  Done in 6.06s.
```

**Comment by flowersinthesand** [comment]
Confirmed it works.

**Pull request merged**
