### PR TITLE
fix/#45 ICON reader fails to read the latest block

### LINKED ISSUE #45: ICON reader fails to read the latest block
```javascript
const actionReader = new IconActionReader({
  startAtBlock: -1
});
```

No block data logged in the console, stopped after a few minutes with the error:

`Error: 120 retries failed`

### PR DESCRIPTION
**Pull request by tiendq**
- Fixed bug
- Refactor reader

Closes #45

### CODE REVIEW

**Comment by manh-vv** [comment]
Could you tell me how does this helps solve the problem?

**Comment by tiendq** [comment]
> Could you tell me how does this helps solve the problem?

There was an undefined error in `IconBlock`.

**Comment by manh-vv** [comment]
> > Could you tell me how does this helps solve the problem?
> 
> There was an undefined error in `IconBlock`.

What is that error?
If it is an `undefined` problem, then it should have been resolved on the master branch already.

**Comment by tiendq** [comment]
> > > Could you tell me how does this helps solve the problem?
> > 
> > 
> > There was an undefined error in `IconBlock`.
> 
> What is that error?
> If it is an `undefined` problem, then it should have been resolved on the master branch already.

It is in the change log, here: https://github.com/lecle/aloxide/pull/52/commits/ff65ade8dad565fe1bd5ea3e526c2f7e0016582b#diff-a6aff99f3d1e5953bd33ab41911b3a7fL32

I don't know if it's fixed on the `master`.

**Comment by manh-vv** [comment]
Close since the bug has been fixed already in the master branch.

**Pull request closed without merging**
